name: Daily Update
on:
  schedule:
    - cron: '0 15 * * *' # 한국 시간 매일 자정 실행
  workflow_dispatch: # 내가 버튼을 눌러서 수동 실행할 수 있는 옵션

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: node scraper.js
      - name: Save data.json to GitHub
        run: |
          git config user.name "Auto-Bot"
          git config user.email "bot@example.com"
          git add data.json
          git commit -m "Update course data" || exit 0
          git push
